export const MENU_ITEMS = {
  DASHBOARD: 'Dashboard',
  PAYMENTS: 'Payments',
  CREATE_INVOICE: 'Create Invoice',
  INVOICE_DETAILS: 'Invoice Details',
  OPERATIONS: 'Operations',
  DEPOSIT_DETAILS: 'Deposit Details',
  DISTRIBUTORS: 'Distributor Profile',
  SETTLEMENT_DETAILS: 'Bank Statement',
  CONFIG: 'Configuration',
  BANKS: 'Banks',
  REPORTS: 'Reports',
  RECONCILIATION: 'Reconciliation',
  TRANSACTION_HISTORY: 'Transaction History',
  INTERMEDIATE_RECONCILIATION: 'Intermediate Reconciliation',
  FINAL_RECONCILIATION: 'Final Reconciliation',
  UNMATCHED: 'Unmatched',
  SETTINGS: 'Settings',
  ALL_TRANSACTIONS: 'All Transactions',
  OUT_STANDING_INVOICE: 'Outstanding Invoice',
};
